config/routes.rb
Donate::Application.routes.draw do
  resources :donations


  root :to => "users#show"  

  devise_for :users

  resources :users    
  resources :donations
end

app/models/donation.rb
class Donation
  include Mongoid::Document
  belongs_to :user

  field :title, type: String, default: ""
  field :description, type: String, default: ""
end

app/models/experience.rb
class Experience < Donation
  include Mongoid::Document
  include Geocoder::Model::Mongoid  

  field :contact, type: String
  field :coordinates, :type => Array
  field :address               # can also be an IP address

  geocoded_by :address               # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  def latitude
    self.coordinates and self.coordinates[0] || nil
  end
  def longtitude
    self.coordinates and self.coordinates[0] || nil
  end
end

app/models/physical_item.rb
class PhysicalItem < Donation
  include Mongoid::Document

  field :height, type: BigDecimal
  field :width, type: BigDecimal
  field :weight, type: BigDecimal

  validates_numericality_of :height, :greater_than_or_equal_to => 0
  validates_numericality_of :width, :greater_than_or_equal_to => 0
  validates_numericality_of :weight, :greater_than_or_equal_to => 0
end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :donations, autosave: true
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""
  field :name, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time
end

app/models/voucher.rb
class Voucher < Donation
  include Mongoid::Document
  field :expires_at, type: Time  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_filter :authenticate_user!      
  # GET /donations
  # GET /donations.json
  def index
  end

  # GET /donations/1
  # GET /donations/1.json
  def show
  end

  # GET /donations/new
  # GET /donations/new.json
  def new
    if params[:type]
      @donation = params[:type].constantize.new
      
      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @donation }
      end
    end  
  end

  # GET /donations/1/edit
  def edit
    @donation = Donation.find(params[:id])
  end

  # POST /donations
  # POST /donations.json
  def create
    if params[:type] == 'Experience' && params[:donation][:coordinates]
      params[:donation][:coordinates] = params[:donation][:coordinates].map{|x| x = x.to_f}
    end
    
    @donation = params[:type].constantize.new(params[:donation])
    @donation.user = current_user

    respond_to do |format|
      if @donation.save
        format.html { redirect_to user_url(current_user), notice: 'Donation was successfully created.' }
        format.json { render json: @donation, status: :created, location: @donation }
      else
        format.html { render action: "new" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /donations/1
  # PUT /donations/1.json
  def update
    @donation = Donation.find(params[:id])

    respond_to do |format|
      if @donation.update_attributes(params[:donation])
        format.html { redirect_to user_url(current_user), notice: 'Donation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @donation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /donations/1
  # DELETE /donations/1.json
  def destroy
    @donation = Donation.find(params[:id])
    @donation.destroy

    respond_to do |format|
      format.html { redirect_to donations_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!    
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!  
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/donations_helper.rb
module DonationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/donations/_form.html.erb
<%= form_for @donation, as: :donation, url: donations_path, html: { multipart: :true, method: 'post'} do |f| %>
  <%= hidden_field_tag 'type', @donation.class.to_s %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>
      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <% if Voucher === @donation %>
    <p>
      <%= f.label :expires_at %><br>
      <%= f.datetime_select :expires_at %>
    </p>
  <% elsif Experience === @donation %>
    <p>
      <%= f.label :contact %><br>
      <%= f.text_field :contact %>
    </p>
      <p>
        <%= f.label :latitude %><br>
        <% if @donation.latitude %>
          <%= f.number_field :latitude %>
        <% else %>  
          <input name="donation[coordinates][]" type="number"/>
        <% end %>  
      </p>
      <p>
        <%= f.label :longtitude %><br>
        <% if @donation.longtitude %>        
          <%= f.number_field :longtitude %>
        <% else %>  
          <input name="donation[coordinates][]" type="number"/>
        <% end %>  
      </p>
    <% unless @donation.coordinates.blank? %>
      <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@donation.latitude}%2C#{@donation.longtitude}" %>
    <% end %>
    
  <% elsif PhysicalItem === @donation %>  
    <p>
      <%= f.label :height %><br>
      <%= f.text_field :height %>
    </p>
    <p>
      <%= f.label :width %><br>
      <%= f.text_field :width %>
    </p>
    <p>
      <%= f.label :weight %><br>
      <%= f.text_field :weight %>
    </p>
  <% end %>  
  


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/edit.html.erb
<h1>Editing donation</h1>

<%= form_for @donation, as: :donation, url: donation_path, html: { multipart: :true, method: 'put'} do |f| %>
  <%= hidden_field_tag 'type', @donation.class.to_s %>
  <% if @donation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@donation.errors.count, "error") %> prohibited this donation from being saved:</h2>
      <ul>
      <% @donation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>

  <% if Voucher === @donation %>
    <p>
      <%= f.label :expires_at %><br>
      <%= f.datetime_select :expires_at %>
    </p>
  <% elsif Experience === @donation %>
    <p>
      <%= f.label :contact %><br>
      <%= f.text_field :contact %>
    </p>
      <p>
        <%= f.label :latitude %><br>
        <% if @donation.latitude %>
          <%= f.number_field :latitude %>
        <% else %>  
          <input name="donation[coordinates][]" type="number"/>
        <% end %>  
      </p>
      <p>
        <%= f.label :longtitude %><br>
        <% if @donation.longtitude %>        
          <%= f.number_field :longtitude %>
        <% else %>  
          <input name="donation[coordinates][]" type="number"/>
        <% end %>  
      </p>
    <% unless @donation.coordinates.blank? %>
      <%= image_tag "http://maps.google.com/maps/api/staticmap?size=450x300&sensor=false&zoom=16&markers=#{@donation.latitude}%2C#{@donation.longtitude}" %>
    <% end %>
  <% elsif PhysicalItem === @donation %>  
    <p>
      <%= f.label :height %><br>
      <%= f.text_field :height %>
    </p>
    <p>
      <%= f.label :width %><br>
      <%= f.text_field :width %>
    </p>
    <p>
      <%= f.label :weight %><br>
      <%= f.text_field :weight %>
    </p>
  <% end %>  
  


  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/donations/index.html.erb
<h1>Listing donations</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @donations.each do |donation| %>
  <tr>
    <td><%= link_to 'Show', donation %></td>
    <td><%= link_to 'Edit', edit_donation_path(donation) %></td>
    <td><%= link_to 'Destroy', donation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Donation', new_donation_path %>

app/views/donations/new.html.erb
<h1>New donation</h1>

<%= render 'form' %>

app/views/donations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_donation_path(@donation) %> |
<%= link_to 'Back', donations_path %>

app/views/home/index.html.erb
<p>User: <%= current_user.name %></p>
<p>Your past donations:</p>

<ul class="list-group">
<% current_user.donations.each do |c| %>
  <li class='donation list-group-item'>
    <span  class='label label-default'><%= c.class.to_s %></span>
     <%= link_to c.title, edit_donation_path(c) %>
  </li>
  <% end %>
</ul>

<%= link_to 'Donate Voucher', new_donation_path(:type => 'Voucher'), :class => "btn" %>
<%= link_to 'Donate Experience', new_donation_path(:type => 'Experience') , :class => "btn" %>
<%= link_to 'Donate Physical Item', new_donation_path(:type => 'PhysicalItem') , :class => "btn" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Donate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <%= yield %>
  </div>  

</body>
</html>

app/views/users/show.html.erb
<div class='page-header'><h1><small>Your past donations:</small></h1></div>
<p id="notice"><%= notice %></p>

<div class='donation-list'>
<ul class="list-group">
<% current_user.donations.each do |c| %>
  <li class='donation list-group-item'>
    <span  class='label label-default'><%= c.class.to_s %></span>
     <%= link_to c.title, edit_donation_path(c) %>
  </li>
  <% end %>
</ul>
</div>

<div class="btn-group">
  <%= link_to 'Donate Voucher', new_donation_path(:type => 'Voucher'), :class => "btn btn-default" %>
  <%= link_to 'Donate Experience', new_donation_path(:type => 'Experience') , :class => "btn btn-default" %>
  <%= link_to 'Donate Physical Item', new_donation_path(:type => 'PhysicalItem') , :class => "btn btn-default" %>
</div>